package dev.sbs.dataflow.stage;

/**
 * Stable wire-format discriminator for a {@link Stage} kind. Used as the {@code "kind"}
 * field in the serialised pipeline definition so renames in the Java code do not break
 * stored pipelines.
 */
public enum StageId {

    /* ---- Source ---- */
    SOURCE_URL,
    SOURCE_PASTE,

    /* ---- Filter ---- */
    FILTER_DOM_TEXT_CONTAINS,
    FILTER_DISTINCT,

    /* ---- Transform ---- */
    PARSE_HTML,
    PARSE_XML,
    PARSE_JSON,
    TRANSFORM_CSS_SELECT,
    TRANSFORM_NODE_TEXT,
    TRANSFORM_NODE_ATTR,
    TRANSFORM_NTH_CHILD,
    TRANSFORM_JSON_PATH,
    TRANSFORM_JSON_FIELD,
    TRANSFORM_REGEX_EXTRACT,
    TRANSFORM_PARSE_INT,
    TRANSFORM_PARSE_LONG,
    TRANSFORM_PARSE_FLOAT,
    TRANSFORM_PARSE_DOUBLE,
    TRANSFORM_PARSE_BOOLEAN,
    TRANSFORM_TRIM,
    TRANSFORM_REPLACE,
    TRANSFORM_SPLIT,
    TRANSFORM_MAP,
    TRANSFORM_LOWERCASE,
    TRANSFORM_UPPERCASE,
    TRANSFORM_STRING_LENGTH,
    TRANSFORM_PREFIX,
    TRANSFORM_SUFFIX,
    TRANSFORM_LIST_LENGTH,
    TRANSFORM_REVERSE,
    TRANSFORM_ABS_INT,
    TRANSFORM_ABS_LONG,
    TRANSFORM_ABS_FLOAT,
    TRANSFORM_ABS_DOUBLE,
    TRANSFORM_NEGATE_INT,
    TRANSFORM_NEGATE_LONG,
    TRANSFORM_NEGATE_FLOAT,
    TRANSFORM_NEGATE_DOUBLE,
    TRANSFORM_TO_STRING,
    TRANSFORM_DOM_CHILDREN,
    TRANSFORM_DOM_PARENT,
    TRANSFORM_DOM_OUTER_HTML,
    TRANSFORM_DOM_OWN_TEXT,
    TRANSFORM_JSON_AS_STRING,
    TRANSFORM_JSON_AS_INT,
    TRANSFORM_JSON_AS_LONG,
    TRANSFORM_JSON_AS_DOUBLE,
    TRANSFORM_JSON_AS_BOOLEAN,
    TRANSFORM_JSON_STRINGIFY,

    /* ---- Collect ---- */
    COLLECT_FIRST,
    COLLECT_LAST,
    COLLECT_LIST,
    COLLECT_SET,
    COLLECT_JOIN,

    /* ---- Compound ---- */
    BRANCH,
    PIPELINE_EMBED,

}
